// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  content: string;
  contentParallax: string;
  contentWrap: string;
  root: string;
  subTitle: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
