// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentParallax: string | undefined;
  contentText: string | undefined;
  contentWrap: null | undefined;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
