// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  menuLink: string | undefined;
  root: string | undefined;
  wrap: string | undefined;
  pokemonLogo: string | undefined;
  menuWrap: string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
